# This is a basic workflow to help you get started with Actions

name: Create and Publish Docker Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
        
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1
      
      - name: Login to the Registry
        uses: docker/login-action@v1
        with:
          username: ${{secrets.registry_username}}
          password: ${{secrets.registry_password}}
      
#       - name: Set the tag
#         run: |
#           if [ -z "${{inputs.tag}}" ]
#           then 
#             echo "final_tag=latest" >> $GITHUB_ENV
#           else
#             echo "final_tag=${{inputs.tag}}">>$GITHUB_ENV
#           fi
      - name: Tagging , Building and Pushing the Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{secrets.registry_username}}/${{inputs.image_name}}:${{inputs.tag}}
          
